spring:
  application:
    name: project-sun-agent
  threads:
    virtual:
      enabled: true
server:
  port: 8080

logging:
  level:
    root: info
  file:
    name: logs/server.log

llm:
  gemini:
    api-key: ${GEMINI_API_KEY}